spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Mysql Settings
    url: jdbc:mysql://localhost:3306/moamoa?serverTimezone=UTC&characterEncoding=UTF-8
    username: moamoa
    password: '0103'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
      use-new-id-generator-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: moamoaofficial0@gmail.com
    password: jhdwizmtwgpsaidm
    properties:
      mail:
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.ssafy.moamoa: debug

security:
  jwt:
    secret-key: 6ec2601c-5280-4761-810b-80a5478ec7ed



